
import { Owner, Rental } from '../types';

export const LOCAL_STORAGE_KEY = 'rentalApp_Final_v4_ownerItems';
export const PIX_CONFIG_KEY = 'rentalApp_Final_v4_pixConfig';

export const DEFAULT_COMPANY_NAME = 'Jobh Imóveis';
export const DEFAULT_COMPANY_DOC = 'CRECI-RJ: 31.387';
export const DEFAULT_COMPANY_PIX_KEY = 'jobh.adm@gmail.com';

export const sampleOwners: Owner[] = [
    { id: '1', name: 'Carlos Silva', cpf: '111.222.333-44', rgCnh: '12.345.678-9', adminFeePercentage: 10, pixKey: 'carlos.silva@email.com', bankDetails: 'Banco A, Ag 123, CC 456' },
    { id: '2', name: 'Fernanda Lima', cpf: '444.555.666-77', rgCnh: '23.456.789-0', adminFeePercentage: 8.5, pixKey: '44455566677', bankDetails: 'Banco B, Ag 456, CC 789' },
    { id: '3', name: 'Ricardo Mendes', cpf: '777.889.999-00', rgCnh: '34.567.890-1', adminFeePercentage: 12, pixKey: 'ricardo.mendes@email.com', bankDetails: 'Banco C, Ag 789, CC 012' },
];

export const sampleRentals: Rental[] = [
    { id: '101', ownerId: '1', owner: 'Carlos Silva', ownerAdminFeePercentage: 10, refNumber: '101', tenantName: 'Mariana Costa', tenantCpf: '123.456.789-10', tenantRgCnh: '11.222.333-4', propertyName: 'Rua das Flores, 123, Apto 101', dueDay: 10, month: 'Maio', year: 2025, isPaid: true, isTransferred: true, waterBill: 50, condoFee: 200, iptu: 80, gasBill: 0, otherItems: [{ id: 'bank1', description: 'Tarifa Bancária', amount: 5 }], ownerItems: [], contractDate: '2024-05-10', lastAdjustmentYear: null, rentDescription: 'Aluguel', rentAmount: 1500 },
    { id: '103', ownerId: '1', owner: 'Carlos Silva', ownerAdminFeePercentage: 10, refNumber: '103', tenantName: 'Ana Julia', tenantCpf: '234.567.890-11', tenantRgCnh: '22.333.444-5', propertyName: 'Rua da Praia, 789, Casa 2', dueDay: 15, month: 'Maio', year: 2025, isPaid: true, isTransferred: true, waterBill: 70, condoFee: 0, iptu: 90, gasBill: 25, otherItems: [{ id: 'bank2', description: 'Tarifa Bancária', amount: 5 }], ownerItems: [{ id: 'owner1', description: 'Manutenção (Prop.)', amount: -150 }], contractDate: '2023-11-15', lastAdjustmentYear: 2024, rentDescription: 'Aluguel', rentAmount: 1800 },
    { id: '102', ownerId: '2', owner: 'Fernanda Lima', ownerAdminFeePercentage: 8.5, refNumber: '202', tenantName: 'Pedro Almeida', tenantCpf: '345.678.901-12', tenantRgCnh: '33.444.555-6', propertyName: 'Av. Principal, 456, Sala 3', dueDay: 5, month: 'Maio', year: 2025, isPaid: true, isTransferred: true, waterBill: 0, condoFee: 450, iptu: 120, gasBill: 0, otherItems: [{ id: 'disc1', description: 'Desconto', amount: -100 }, { id: 'bank9', description: 'Tarifa Bancária', amount: 5 }], ownerItems: [], contractDate: '2024-05-01', lastAdjustmentYear: null, rentDescription: 'Aluguel', rentAmount: 2200 },
    { id: '104', ownerId: '3', owner: 'Ricardo Mendes', ownerAdminFeePercentage: 12, refNumber: '301', tenantName: 'Lucas Ferreira', tenantCpf: '456.789.012-13', tenantRgCnh: '44.555.666-7', propertyName: 'Travessa dos Coqueiros, 10', dueDay: 20, month: 'Junho', year: 2025, isPaid: true, isTransferred: false, waterBill: 120, condoFee: 0, iptu: 250, gasBill: 0, otherItems: [{ id: 'bank10', description: 'Tarifa Bancária', amount: 5 }, { id: 'multa1', description: 'Multa Atraso', amount: 350 }, { id: 'juros1', description: 'Juros Atraso', amount: 70 }], ownerItems: [], contractDate: '2023-06-20', lastAdjustmentYear: 2024, rentDescription: 'Aluguel', rentAmount: 3500 },

    // 20 Inquilinos Fictícios para Teste (Janeiro 2026)
    { id: 't1', ownerId: '1', owner: 'Carlos Silva', refNumber: '1001', tenantName: 'Bruno Souza', propertyName: 'Rua A, 10, Ap 101', dueDay: 5, month: 'Janeiro', year: 2026, rentAmount: 1200, isPaid: true, isTransferred: false, waterBill: 50, condoFee: 150, iptu: 50, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't2', ownerId: '1', owner: 'Carlos Silva', refNumber: '1002', tenantName: 'Carla Dias', propertyName: 'Rua A, 10, Ap 102', dueDay: 5, month: 'Janeiro', year: 2026, rentAmount: 1300, isPaid: false, isTransferred: false, waterBill: 60, condoFee: 150, iptu: 50, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't3', ownerId: '1', owner: 'Carlos Silva', refNumber: '1003', tenantName: 'Daniel Rocha', propertyName: 'Rua A, 10, Ap 201', dueDay: 10, month: 'Janeiro', year: 2026, rentAmount: 1400, isPaid: true, isTransferred: true, waterBill: 55, condoFee: 160, iptu: 55, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't4', ownerId: '1', owner: 'Carlos Silva', refNumber: '1004', tenantName: 'Eliana Moraes', propertyName: 'Rua A, 10, Ap 202', dueDay: 10, month: 'Janeiro', year: 2026, rentAmount: 1250, isPaid: true, isTransferred: false, waterBill: 50, condoFee: 150, iptu: 50, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't5', ownerId: '1', owner: 'Carlos Silva', refNumber: '1005', tenantName: 'Fabio Costa', propertyName: 'Rua B, 20, Casa 1', dueDay: 15, month: 'Janeiro', year: 2026, rentAmount: 2000, isPaid: false, isTransferred: false, waterBill: 100, condoFee: 0, iptu: 120, gasBill: 50, otherItems: [], ownerItems: [] },
    { id: 't6', ownerId: '1', owner: 'Carlos Silva', refNumber: '1006', tenantName: 'Gabriela Silva', propertyName: 'Rua B, 20, Casa 2', dueDay: 15, month: 'Janeiro', year: 2026, rentAmount: 2100, isPaid: true, isTransferred: true, waterBill: 110, condoFee: 0, iptu: 130, gasBill: 60, otherItems: [], ownerItems: [] },

    { id: 't7', ownerId: '2', owner: 'Fernanda Lima', refNumber: '2001', tenantName: 'Hugo Alves', propertyName: 'Av Central, 500, Sala 1', dueDay: 5, month: 'Janeiro', year: 2026, rentAmount: 3000, isPaid: true, isTransferred: false, waterBill: 80, condoFee: 400, iptu: 200, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't8', ownerId: '2', owner: 'Fernanda Lima', refNumber: '2002', tenantName: 'Igor Santos', propertyName: 'Av Central, 500, Sala 2', dueDay: 5, month: 'Janeiro', year: 2026, rentAmount: 3200, isPaid: true, isTransferred: true, waterBill: 85, condoFee: 400, iptu: 210, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't9', ownerId: '2', owner: 'Fernanda Lima', refNumber: '2003', tenantName: 'Juliana Lima', propertyName: 'Av Central, 500, Sala 3', dueDay: 5, month: 'Janeiro', year: 2026, rentAmount: 3100, isPaid: false, isTransferred: false, waterBill: 80, condoFee: 400, iptu: 205, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't10', ownerId: '2', owner: 'Fernanda Lima', refNumber: '2004', tenantName: 'Kleber Souza', propertyName: 'Rua do Porto, 33, Ap 10', dueDay: 10, month: 'Janeiro', year: 2026, rentAmount: 1800, isPaid: true, isTransferred: false, waterBill: 60, condoFee: 250, iptu: 100, gasBill: 30, otherItems: [], ownerItems: [] },
    { id: 't11', ownerId: '2', owner: 'Fernanda Lima', refNumber: '2005', tenantName: 'Laura Martins', propertyName: 'Rua do Porto, 33, Ap 11', dueDay: 10, month: 'Janeiro', year: 2026, rentAmount: 1850, isPaid: true, isTransferred: false, waterBill: 65, condoFee: 250, iptu: 100, gasBill: 35, otherItems: [], ownerItems: [] },
    { id: 't12', ownerId: '2', owner: 'Fernanda Lima', refNumber: '2006', tenantName: 'Marcos Paulo', propertyName: 'Rua do Porto, 33, Ap 12', dueDay: 10, month: 'Janeiro', year: 2026, rentAmount: 1900, isPaid: false, isTransferred: false, waterBill: 70, condoFee: 250, iptu: 110, gasBill: 40, otherItems: [], ownerItems: [] },

    { id: 't13', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3001', tenantName: 'Natalia Torres', propertyName: 'Est. Velha, 99, Galpão A', dueDay: 1, month: 'Janeiro', year: 2026, rentAmount: 5000, isPaid: true, isTransferred: true, waterBill: 200, condoFee: 0, iptu: 300, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't14', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3002', tenantName: 'Otavio Mesquita', propertyName: 'Est. Velha, 99, Galpão B', dueDay: 1, month: 'Janeiro', year: 2026, rentAmount: 5500, isPaid: true, isTransferred: false, waterBill: 220, condoFee: 0, iptu: 320, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't15', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3003', tenantName: 'Patricia Gomes', propertyName: 'Res. Colina, Bloco 1, Ap 101', dueDay: 20, month: 'Janeiro', year: 2026, rentAmount: 900, isPaid: true, isTransferred: false, waterBill: 40, condoFee: 100, iptu: 30, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't16', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3004', tenantName: 'Quintino Bocaiuva', propertyName: 'Res. Colina, Bloco 1, Ap 102', dueDay: 20, month: 'Janeiro', year: 2026, rentAmount: 950, isPaid: false, isTransferred: false, waterBill: 45, condoFee: 100, iptu: 35, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't17', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3005', tenantName: 'Roberto Carlos', propertyName: 'Res. Colina, Bloco 2, Ap 201', dueDay: 20, month: 'Janeiro', year: 2026, rentAmount: 920, isPaid: true, isTransferred: false, waterBill: 42, condoFee: 100, iptu: 32, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't18', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3006', tenantName: 'Sabrina Sato', propertyName: 'Res. Colina, Bloco 2, Ap 202', dueDay: 20, month: 'Janeiro', year: 2026, rentAmount: 980, isPaid: true, isTransferred: true, waterBill: 48, condoFee: 100, iptu: 38, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't19', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3007', tenantName: 'Tiago Leifert', propertyName: 'Res. Colina, Bloco 3, Ap 301', dueDay: 20, month: 'Janeiro', year: 2026, rentAmount: 1100, isPaid: false, isTransferred: false, waterBill: 50, condoFee: 110, iptu: 40, gasBill: 0, otherItems: [], ownerItems: [] },
    { id: 't20', ownerId: '3', owner: 'Ricardo Mendes', refNumber: '3008', tenantName: 'Ursula Andress', propertyName: 'Res. Colina, Bloco 3, Ap 302', dueDay: 20, month: 'Janeiro', year: 2026, rentAmount: 1150, isPaid: true, isTransferred: false, waterBill: 55, condoFee: 115, iptu: 45, gasBill: 0, otherItems: [], ownerItems: [] },
];
